---
- name: Build NGINX Docker image
  hosts: localhost
  become: true

  tasks:
    - name: Copy Dockerfile
      copy:
        src: /home/user/example_nginx/dockerfile
        dest: /tmp/Dockerfile

    - name: Build Docker image
      docker_image:
        build:
          path: /tmp
          pull: yes
        name: nginx
        tag: latest
